The first prints 3, the second is an error because x is not available in the scope. 